### ISSUE TITLE
Cipher spec support

### ISSUE THREAD

**Issue by chris-x86-64** [moriyoshi/devproxy#4]
Hi,

I thought it would be nice to be able to test various TLS implementations when running test sites through devproxy.
Is there any way to tweak SSL/TLS specifications?
I would like to do something like this:

```yaml
# This example is in LDAP style but it's really up to the developer.
tls:
  version: !1.0:1.1:1.2
  ciphers: HIGH:MEDIUM:!MD5:!RC4:!3DES
```

Thanks.

**Comment by moriyoshi** [comment]
Hi,

You can specify the ciphers by either `tls/server/ciphers` for connections between devproxy and the upstream, or `tls/client/ciphers` for connections between the client and devproxy.

The complete list of cipher identifiers are here:
https://github.com/moriyoshi/devproxy/blob/master/config.go#L111-L144

E.g.
```
tls:
   server:
      ciphers:
         - RSA_WITH_AES_128_CBC_SHA
         - RSA_WITH_AES_256_CBC_SHA
    client:
      ciphers:
         - RSA_WITH_AES_256_CBC_SHA
```
